### ISSUE TITLE
A user should be able to exists in multiple groups

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-streaming#27]
Currently only one `group_id` store in a user object, which isn't the correct implementation. This impact keywords save and trends calculation.

**Comment by rngadam** [comment]
see : https://github.com/transist/echidna-streaming/edit/master/bin/worker.rb

this retrieves a single id instead of an array of id - then needs to iterate through that list and generate one message to the segmenter for each group.

```
      group_id = User.new("id" => message["body"]["user_id"], "type" => message["body"]["user_type"])['group_id']
      $redis.lpush "dicts/messages", MultiJson.encode(
        type: "segment",
        body: message["body"].slice("text", "timestamp").merge(group_id: group_id, source_id: message["body"]["id"])
      )
```

Right now, Redis groups have all users but Redis users don't have all groups. It should be a N:N relation, it's a N:1 relation now...

Data impact: right now, messages only get segmented and counted for a single group, causing the per-panel data to be under-counted.

If we apply Rainux patch, historical counts are going to wrong, but correct as the data comes in.
